## Pandas

In [1]:
import numpy as np
import pandas as pd

In [ ]:
## Pandas Series
data = np.array([1,2,3,4,5])
series = pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [3]:
# Series from Dictionary
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
## Dataframe
# Create dataframe from a dictionary of list 

data = {
    'Name': ['Krish', 'John', 'Jack'],
    'Age': [25, 30, 45],
    'City': ['Bangalore', 'New york', 'California']
}

dict_df = pd.DataFrame(data)
dict_df

    Name  Age        City
0  Krish   25   Bangalore
1   John   30    New york
2   Jack   45  California

In [6]:
print(type(dict_df))

<class 'pandas.DataFrame'>

In [7]:
np.array(dict_df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New york'],
       ['Jack', 45, 'California']], dtype=object)

In [8]:
## Create Dataframe from a list of dictionaires

data = [
     {'Name' : 'Krish','Age': 32, 'City':'Bangalore'},
     {'Name' : 'John','Age': 22, 'City':'Texas'},
     {'Name' : 'Jack','Age': 35, 'City':'LA'},
     {'Name' : 'Charlie','Age': 52, 'City':'New York'},

]

df = pd.DataFrame(data)
df

      Name  Age       City
0    Krish   32  Bangalore
1     John   22      Texas
2     Jack   35         LA
3  Charlie   52   New York

In [2]:
## CSV to dataframe
df = pd.read_csv('sales.csv')
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,9/28/2016,579463422,11/1/2016,4958,9.33,6.92,46258.14,34309.36,11948.78

In [9]:
df.sample(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
203,Europe,Malta,Meat,Offline,C,6/26/2014,662623488,7/11/2014,3870,421.89,364.69,1632714.30,1411350.30,221364.00
1136,Europe,Kosovo,Office Supplies,Offline,M,8/1/2012,760280358,8/21/2012,2708,651.21,524.96,1763476.68,1421591.68,341885.00
1082,Europe,Finland,Baby Food,Offline,L,4/21/2017,564173543,4/26/2017,343,255.28,159.42,87561.04,54681.06,32879.98
874,Europe,Armenia,Household,Online,L,2/19/2012,104165685,3/6/2012,3796,668.27,502.54,2536752.92,1907641.84,629111.08
957,Europe,Slovakia,Snacks,Offline,C,11/16/2016,536095750,12/26/2016,1500,152.58,97.44,228870.00,146160.00,82710.00

In [10]:
df.tail()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1325,Europe,Norway,Personal Care,Offline,M,1/14/2014,634033286,1/15/2014,3394,81.73,56.67,277391.62,192337.98,85053.64
1326,Europe,Ukraine,Cereal,Offline,L,4/14/2014,559183347,5/21/2014,3633,205.70,117.11,747308.10,425460.63,321847.47
1327,Europe,Armenia,Meat,Offline,M,11/9/2015,781416594,12/23/2015,7390,421.89,364.69,3117767.10,2695059.10,422708.00
1328,Europe,Denmark,Clothes,Offline,H,5/9/2012,713357150,6/3/2012,7088,109.28,35.84,774576.64,254033.92,520542.72
1329,Europe,Finland,Clothes,Online,L,4/22/2014,906794202,5/11/2014,9410,109.28,35.84,1028324.80,337254.40,691070.40

In [11]:
df.shape

(1330, 14)

In [12]:
# States the number of rows having null values / missing values 
df.isnull().sum()

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1330 entries, 0 to 1329
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          1330 non-null   str
 1   Country         1330 non-null   str
 2   Item Type       1330 non-null   str
 3   Sales Channel   1330 non-null   str
 4   Order Priority  1330 non-null   str
 5   Order Date      1330 non-null   str
 6   Order ID        1330 non-null   int64
 7   Ship Date       1330 non-null   str
 8   Units Sold      1330 non-null   int64
 9   Unit Price      1330 non-null   float64
 10  Unit Cost       1330 non-null   float64
 11  Total Revenue   1330 non-null   float64
 12  Total Cost      1330 non-null   float64
 13  Total Profit    1330 non-null   float64
dtypes: float64(5), int64(2), str(7)
memory usage: 145.6 KB

In [28]:
# df.dtypes
# df.describe()

In [12]:
dict_df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [13]:
type(dict_df['Name'])

pandas.Series

In [14]:
dict_df

    Name  Age        City
0  Krish   25   Bangalore
1   John   30    New york
2   Jack   45  California

In [15]:
dict_df.loc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [16]:
dict_df.iloc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [17]:
# Accessing specific element
dict_df.at[1,'Age']

np.int64(30)

In [18]:
dict_df.iat[2,2]

'California'

In [19]:
# Adding a column
dict_df['Salary'] = [50000, 60000, 70000]
dict_df

    Name  Age        City  Salary
0  Krish   25   Bangalore   50000
1   John   30    New york   60000
2   Jack   45  California   70000

In [20]:
# Remove a column
dict_df.drop('Salary', axis=1, inplace=True)

In [21]:
dict_df

    Name  Age        City
0  Krish   25   Bangalore
1   John   30    New york
2   Jack   45  California

In [22]:
# Add age to column
dict_df['Age'] += 1
dict_df

    Name  Age        City
0  Krish   26   Bangalore
1   John   31    New york
2   Jack   46  California

In [23]:
# drop a row
dict_df.drop(0, inplace=True)

In [24]:
dict_df

   Name  Age        City
1  John   31    New york
2  Jack   46  California